/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypanels;

import java.awt.Color;
import static java.lang.Math.abs;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Lasanga
 */
public class LoginPanel extends javax.swing.JPanel {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    SignupPanel signupPanel;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }
    
    
    public void setSignupPanel(SignupPanel signupPanel){
        this.signupPanel = signupPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signuplbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordMouseReleased(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        signuplbl.setText("Sign up");
        signuplbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signuplblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signuplblMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signuplblMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signuplbl))
                    .addComponent(password)
                    .addComponent(username))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginBtn)
                    .addComponent(signuplbl))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signuplblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplblMouseReleased
        // TODO add your handling code here:
        this.setVisible(false);
        signupPanel.setVisible(true);
    }//GEN-LAST:event_signuplblMouseReleased

    private void signuplblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplblMouseEntered
        // TODO add your handling code here:
        signuplbl.setForeground(Color.BLUE);
    }//GEN-LAST:event_signuplblMouseEntered

    private void signuplblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplblMouseExited
        // TODO add your handling code here:
        
        signuplbl.setForeground(Color.BLACK);
    }//GEN-LAST:event_signuplblMouseExited

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        conn = SQLite.ConnectSqlite();
        String keystroke;
        String sql = "select * from login where username=? and password=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, username.getText());
            pst.setString(2, password.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                System.out.println(rs.getString("first_name"));
                System.out.println(rs.getString("last_name"));
                keystroke = rs.getString("keystroke");
                ArrayList<String> a = new ArrayList<String>();
                a.addAll(Arrays.asList(keystroke.substring(1, keystroke.length() - 1).split(", ")));
                ArrayList<Long> b = new ArrayList<Long>();
                for(String string : a){
                    b.add(Long.parseLong(string));
                }
                int total=0;
                int size=pressed.size();
                System.out.println(pressed);
                System.out.println(b);
                if(size==b.size()){
                    for(int i=1; i<size;i++){
                        total+=abs((pressed.get(i)-b.get(i))/100000);
                    }
                }
                int loginfact = total/size;
                System.out.println(loginfact);
                if(loginfact<200){
                    JOptionPane.showMessageDialog(null, "Welcome "+rs.getString("first_name"), "login states", JOptionPane.INFORMATION_MESSAGE);
                    password.setText(null);
                    pressed.clear();released.clear();
                }else{
                JOptionPane.showMessageDialog(null, "keystroke dynamics are different", "access denied", JOptionPane.ERROR_MESSAGE);
                password.setText(null);
                pressed.clear();released.clear();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Username or Password", "access denied", JOptionPane.ERROR_MESSAGE);
                password.setText(null);
                pressed.clear();released.clear();
            }
            conn.close();
        }
        catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_loginBtnActionPerformed

    long lastPressedTime = System.nanoTime();
    long lastReleasedTime = System.nanoTime();
    long nowTime = System.nanoTime();
    long dif;
    ArrayList<Long> pressed = new ArrayList<>();
    ArrayList<Long> released = new ArrayList<>();
    ArrayList<Integer> pressTest = new ArrayList<>();
    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if(c==8){password.setText(null);}
        nowTime = System.nanoTime();
        dif = nowTime - lastPressedTime;
        lastPressedTime = nowTime;
        pressed.add(dif);
    }//GEN-LAST:event_passwordKeyPressed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        if(password.getPassword().length==0){pressed.clear();released.clear();}
    }//GEN-LAST:event_passwordKeyReleased

    private void passwordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseReleased
        // TODO add your handling code here:
        lastPressedTime = System.nanoTime();
        lastReleasedTime = System.nanoTime();
    }//GEN-LAST:event_passwordMouseReleased

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel signuplbl;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
